CKEDITOR.addStylesSet('spip-styles',
	[
		{ name: 'Gras', element: 'strong', attributes: { 'class': 'spip' }},
		{ name: 'Italique', element: 'i', attributes: { 'class': 'spip' }},
		{ name: 'Intertitre', element: 'h3', attributes: { 'class': 'spip' }},
		{ name: 'Noir', element: 'span', styles: { 'color': 'black' }},
		{ name: 'Rouge', element: 'span', styles: { 'color': 'red' }},
		{ name: 'Marron', element: 'span', styles: { 'color': 'maroon' }},
		{ name: 'Vert', element: 'span', styles: { 'color': 'green' }},
		{ name: 'Olive', element: 'span', styles: { 'color': 'olive' }},
		{ name: 'Bleu marine', element: 'span', styles: { 'color': 'navy' }},
		{ name: 'Violet', element: 'span', styles: { 'color': 'purple' }},
		{ name: 'Gris', element: 'span', styles: { 'color': 'gray' }},
		{ name: 'Argent', element: 'span', styles: { 'color': 'silver' }},
		{ name: 'Vert clair', element: 'span', styles: { 'color': 'chartreuse' }},
		{ name: 'Bleu', element: 'span', styles: { 'color': 'blue' }},
		{ name: 'Fuchsia', element: 'span', styles: { 'color': 'fuchsia' }},
		{ name: 'Bleu clair', element: 'span', styles: { 'color': 'aqua' }},
		{ name: 'Blanc', element: 'span', styles: { 'color': 'white' }},
		{ name: 'Bleu azure', element: 'span', styles: { 'color': 'azure' }},
		{ name: 'Beige', element: 'span', styles: { 'color': 'bisque' }},
		{ name: 'Brun', element: 'span', styles: { 'color': 'brown' }},
		{ name: 'Bleu violet', element: 'span', styles: { 'color': 'blueviolet' }},
		{ name: 'Chocolat', element: 'span', styles: { 'color': 'chocolate' }},
		{ name: 'Roce clair', element: 'span', styles: { 'color': 'cornsilk' }},
		{ name: 'Vert foncé', element: 'span', styles: { 'color': 'darkgreen' }},
		{ name: 'Orange foncé', element: 'span', styles: { 'color': 'darkorange' }},
		{ name: 'Mauve foncé', element: 'span', styles: { 'color': 'darkorchid' }},
		{ name: 'Bleu ciel', element: 'span', styles: { 'color': 'deepskyblue' }},
		{ name: 'Or', element: 'span', styles: { 'color': 'gold' }},
		{ name: 'Ivoire', element: 'span', styles: { 'color': 'ivory' }},
		{ name: 'Orange', element: 'span', styles: { 'color': 'orange' }},
		{ name: 'Lavande', element: 'span', styles: { 'color': 'lavender' }},
		{ name: 'Rose', element: 'span', styles: { 'color': 'pink' }},
		{ name: 'Prune', element: 'span', styles: { 'color': 'plum' }},
		{ name: 'Saumon', element: 'span', styles: { 'color': 'salmon' }},
		{ name: 'Neige', element: 'span', styles: { 'color': 'snow' }},
		{ name: 'Turquoise', element: 'span', styles: { 'color': 'turquoise' }},
		{ name: 'Jaune paille', element: 'span', styles: { 'color': 'wheat' }},
		{ name: 'Jaune', element: 'span', styles: { 'color': 'yellow' }},

		{ name: 'Fond Noir', element: 'span', styles: { 'background-color': 'black' }},
		{ name: 'Fond Rouge', element: 'span', styles: { 'background-color': 'red' }},
		{ name: 'Fond Marron', element: 'span', styles: { 'background-color': 'maroon' }},
		{ name: 'Fond Vert', element: 'span', styles: { 'background-color': 'green' }},
		{ name: 'Fond Olive', element: 'span', styles: { 'background-color': 'olive' }},
		{ name: 'Fond Bleu marine', element: 'span', styles: { 'background-color': 'navy' }},
		{ name: 'Fond Violet', element: 'span', styles: { 'background-color': 'purple' }},
		{ name: 'Fond Gris', element: 'span', styles: { 'background-color': 'gray' }},
		{ name: 'Fond Argent', element: 'span', styles: { 'background-color': 'silver' }},
		{ name: 'Fond Vert clair', element: 'span', styles: { 'background-color': 'chartreuse' }},
		{ name: 'Fond Bleu', element: 'span', styles: { 'background-color': 'blue' }},
		{ name: 'Fond Fuchsia', element: 'span', styles: { 'background-color': 'fuchsia' }},
		{ name: 'Fond Bleu clair', element: 'span', styles: { 'background-color': 'aqua' }},
		{ name: 'Fond Blanc', element: 'span', styles: { 'background-color': 'white' }},
		{ name: 'Fond Bleu azure', element: 'span', styles: { 'background-color': 'azure' }},
		{ name: 'Fond Beige', element: 'span', styles: { 'background-color': 'bisque' }},
		{ name: 'Fond Brun', element: 'span', styles: { 'background-color': 'brown' }},
		{ name: 'Fond Bleu violet', element: 'span', styles: { 'background-color': 'blueviolet' }},
		{ name: 'Fond Chocolat', element: 'span', styles: { 'background-color': 'chocolate' }},
		{ name: 'Fond Roce clair', element: 'span', styles: { 'background-color': 'cornsilk' }},
		{ name: 'Fond Vert foncé', element: 'span', styles: { 'background-color': 'darkgreen' }},
		{ name: 'Fond Orange foncé', element: 'span', styles: { 'background-color': 'darkorange' }},
		{ name: 'Fond Mauve foncé', element: 'span', styles: { 'background-color': 'darkorchid' }},
		{ name: 'Fond Bleu ciel', element: 'span', styles: { 'background-color': 'deepskyblue' }},
		{ name: 'Fond Or', element: 'span', styles: { 'background-color': 'gold' }},
		{ name: 'Fond Ivoire', element: 'span', styles: { 'background-color': 'ivory' }},
		{ name: 'Fond Orange', element: 'span', styles: { 'background-color': 'orange' }},
		{ name: 'Fond Lavande', element: 'span', styles: { 'background-color': 'lavender' }},
		{ name: 'Fond Rose', element: 'span', styles: { 'background-color': 'pink' }},
		{ name: 'Fond Prune', element: 'span', styles: { 'background-color': 'plum' }},
		{ name: 'Fond Saumon', element: 'span', styles: { 'background-color': 'salmon' }},
		{ name: 'Fond Neige', element: 'span', styles: { 'background-color': 'snow' }},
		{ name: 'Fond Turquoise', element: 'span', styles: { 'background-color': 'turquoise' }},
		{ name: 'Fond Jaune paille', element: 'span', styles: { 'background-color': 'wheat' }},
		{ name: 'Fond Jaune', element: 'span', styles: { 'background-color': 'yellow' }}
	]
) ;
